### ISSUE TITLE
Deposit LiveCoMS TOC image

### ISSUE THREAD

**Issue by davidlmobley** [davesmith4398/best_practice_membranes#8]
Any chance you could deposit the LiveCoMS representative image (you might call it the "table of contents" image) here, ideally also with a higher resolution version? For the journal itself the one we have is fine, but this may get picked up by press and your image is a good one to use for that (with credit of course!) if it's available in higher resolution form.

**Comment by mrshirts** [comment]
![image](https://user-images.githubusercontent.com/4274132/50569791-97528300-0d2c-11e9-8f6e-84deb00efbd9.png)

FWIW, here's the high res image.

**Comment by davesmith4398** [comment]
Hi Michael and David,

Thank you for locating the high-res version. This seems to be resolved on the C&E News end as well (separate chain of emails).

Thanks,

Dave
